FROM node:22-alpine

# RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# RUN npm rebuild @redis/client --build-from-source

CMD ["npm", "run", "dev"]