@baseUrl=http://localhost:8080
@healthBaseUrl={{baseUrl}}/health
@apiBaseUrl={{baseUrl}}/api/v1
@authBaseUrl={{apiBaseUrl}}/auth

@authToken = {{login.response.body.user.token}}
### Auth Routes

### Login
# @name login
POST {{authBaseUrl}}/users/login HTTP/1.1
Content-Type: application/json

{
  "user": {
    "email": "email3@email.com",
    "password": "password3"
  }
}


### Register
# @name register
POST {{authBaseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "user": {
    "email": "email3@email.com",
    "password": "password3",
    "username": "username3"
  }
}

### Current User
GET {{authBaseUrl}}/user HTTP/1.1
Authorization: Bearer {{authToken}}

### Update User
PUT {{authBaseUrl}}/user HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "user": {
    "username": "Jonathan Atia"
  }
}